# ベースイメージの取得
# ※取得済みの場合は、それを使用する
FROM python:3.9-slim

# メタ情報の付与
# ※MAINTAINERは廃止予定
LABEL maintainer="Nalu m"
LABEL version="1.0"
LABEL description="シンプルなPythonイメージです。"

# 作業ディレクトリを変更
# ※ディレクトリがなければ作成されるので心配なし
WORKDIR /tmp/mydir